# Generated by Django 6.0.7 on 2026-07-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField(blank=True, help_text='date of the event', null=True)),
                ('event_location', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('event_image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, help_text=' send this person a positive affirmations', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AudioSegments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_segment', models.FileField(upload_to='audio/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_segments', to='Events.events')),
            ],
            options={
                'verbose_name_plural': 'Audio segments',
            },
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer', models.TextField()),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.pastor')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSegments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_segment', models.FileField(upload_to='video/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_segments', to='Events.events')),
            ],
        ),
    ]
