# Generated by Django 6.0.7 on 2026-07-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_dailybread_eventsales'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
            ],
        ),
    ]
