# Generated by Django 6.0.7 on 2026-07-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_chatbot_delete_psa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayer',
            name='pastor',
        ),
        migrations.AddField(
            model_name='pastor',
            name='audio_segment',
            field=models.FileField(blank=True, upload_to='prayers_for_those_in_need/'),
        ),
        migrations.AddField(
            model_name='pastor',
            name='prayer',
            field=models.TextField(blank=True, help_text='add a prayer'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_image',
            field=models.ImageField(upload_to='events/'),
        ),
        migrations.DeleteModel(
            name='AudioSegments',
        ),
        migrations.DeleteModel(
            name='Prayer',
        ),
    ]
