# Generated by Django 6.0.7 on 2026-08-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_eventsales_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
    ]
