# Generated by Django 6.0.7 on 2026-08-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_biblechat'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalScripture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, unique=True)),
                ('reference', models.CharField(max_length=100)),
                ('reflection', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BibleChat',
        ),
    ]
