# Generated by Django 6.0.7 on 2026-07-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scripture_name', models.TextField(help_text='Bible reference')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(help_text=' the person who wrote the passage')),
            ],
        ),
        migrations.CreateModel(
            name='EventSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(help_text=' products that we have for sale')),
                ('description', models.TextField(help_text='a description of the product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
