# Generated by Django 6.0.7 on 2026-07-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_psa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('chat', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='PSA',
        ),
    ]
