# Generated by Django 6.0.7 on 2026-08-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_remove_prayer_pastor_pastor_audio_segment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsales',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
